version: '3'
services:
  apache:
    build: apache
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 80:80
    networks:
      - backend

  php:
    build: php-fpm
    restart: unless-stopped
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 9000:9000
    networks:
      - backend

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

  mailhog:
    build: mailhog
    restart: unless-stopped
    volumes:
      - mail-data:/home/mailhog/maildir
    environment:
      - MH_MAILDIR_PATH=/home/mailhog/maildir
      - MH_STORAGE=maildir
    ports:
      - 8025:8025
    networks:
      - backend


  mongodb:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks:
      - backend

volumes:
  mysql-data:
  mail-data:
  mongodb-data:

networks:
  backend:
